# Don't forget to add your plugin to config.panda!

# If you need custom CFLAGS or LIBS, set them up here
# CFLAGS+=
# LIBS+=

# The main rule for your plugin. List all object-file dependencies.
$(PLUGIN_TARGET_DIR)/panda_$(PLUGIN_NAME).so: \
	$(PLUGIN_OBJ_DIR)/Windows_7_x86_prototypes_fixed_for_panda.txt.trc.o \
    $(PLUGIN_OBJ_DIR)/Windows_7_x86_prototypes_fixed_for_panda.txt.trc.h.dump.o
