#ifndef __TRACERTIME_H__
#define __TRACERTIME_H__

#define TRACERID_TIME__VIRT_BEFORE_MEM_WRITE (1)
#define TRACERID_TIME__BEFORE_INSN_TRANSLATE (2)
#define TRACERID_TIME__BEFORE_INSN_EXEC (3)
#define TRACERID_TIME__BEFORE_BLOCK_EXEC (4)
#define TRACERID_TIME__CAPSTONE_INSN_DISASM (5)
#define TRACERID_TIME__BEFORE_CALLER_ANALYSIS (6)
#define TRACERID_TIME__CALLER_ANALYSIS (7)


const char * id2str(uint32_t id);

#endif